# 조합하기
output_j = "{:+5d}".format(52)
output_k = "{:+5d}".format(-52)
output_l = "{:=+5d}".format(52)
output_m = "{:=+5d}".format(-52)
output_n = "{:+05d}".format(52)
output_o = "{:+05d}".format(-52)

print("# 조합하기")
print(output_j)
print(output_k)
print(output_l)
print(output_m)
print(output_n)
print(output_o)
